module.exports.values = ["Login",
	"Username",
	"Password",
	"Remember me",
	"Forgot Password?",
	"Android",
	"iOS",
	"Windows",
	"Logout",
	"Web Clips",
	"No apps, yet.",
	"No apps available, yet! When the administration uploads, apps will show up here.",
	"You don't have permission to view apps.",
	"You don't have permission to view device types.",
	"You don't have permission to view uninstalled users",
	"Some permissions are not given to manage subscriptions for a release",
	"You don't have permission to add reviews",
	"You don't have permission to view reviews.",
	"You don't have permission to view subscription details",
	"You don't have permission to view uninstalled roles.",
	"You don't have permission to view installed groups.",
	"You don't have permission to view installed devices.",
	"You don't have permission to view roles.",
	"You don't have permission to view groups.",
	"You don't have permission to view devices.",
	"Error occurred while trying to load device types.",
	"There was a problem",
	"Error occurred while trying to logout.",
	"Error occurred while trying to load releases.",
	"We are unable to add your review right now.",
	"We are unable to update your review right now.",
	"We were unable to delete the review..",
	"Error occurred while trying to load reviews.",
	"Error occurred while trying to load ratings.",
	"Error occurred while trying to get your review.",
	"Error occurred while trying to retrieve device filters.",
	"Something went wrong when trying to load subscription data.",
	"Error occurred while installing the app.",
	"Error occurred while uninstalling the app.",
	"Error occurred while trying to load users.",
	"Error occurred while trying to load roles.",
	"Error occurred while trying to load groups.",
	"Error occurred while trying to load devices.",
	"Done!",
	"Your review has been posted successfully.",
	"Your review has been update successfully.",
	"The review has been deleted successfully.",
	"Operation triggered!",
	"apps",
	"Version",
	"Install",
	"Uninstall",
	"Download",
	"Subscribe",
	"CATEGORIES",
	"TAGS",
	"META DATA",
	"MY REVIEW",
	"REVIEWS",
	"No meta data available.",
	"Schedule Install",
	"Schedule Uninstall",
	"Share your experience with your community by adding a review.",
	"Are you sure delete this review ?",
	"Read All Reviews",
	"The following are the subscription details of the application in each respective device.",
	"total",
	"Edit",
	"Delete",
	"not-found",
	"Select users",
	"Select Time",
	"Search Devices",
	"Search roles",
	"Search groups",
	"Search by Action",
	"Search by Action Status",
	"Search by Status",
	"Search by Owner",
	"Search by Ownership",
	"Search by Device Name",
	"Submit",
	"Cancel",
	"Delete",
	"Yes",
	"No",
	"Refresh",
	"Tell others what you think about this app. Would you recommend it, and why?",
	"Add review",
	"Edit review",
	"Posting your review...",
	"Add a review",
	"Action",
	"Device",
	"IMEI",
	"Modal",
	"Group",
	"Groups",
	"Devices by Group",
	"User",
	"Role",
	"Owner",
	"Ownership",
	"Action Status",
	"Action Type",
	"Device Status",
	"Status",
	"Last Updated",
	"Device Name",
	"Triggered By",
	"Action Triggered At",
	"OS Version",
	"Start uninstalling the application for one or more roles by entering the corresponding role name. Select uninstall to automatically start uninstalling the application for the respective user role/roles.",
	"Start installing the application for one or more roles by entering the corresponding role name. Select install to automatically start downloading the application for the respective user role/roles.",
	"Start uninstalling the application for one or more groups by entering the corresponding group name. Select uninstall to automatically start uninstalling the application for the respective device group/ groups.",
	"Start installing the application for one or more groups by entering the corresponding group name. Select install to automatically start downloading the application for the respective device group/ groups.",
	"Start uninstalling the application for devices by selecting the corresponding devices. Select uninstall to automatically start uninstalling the application for the respective devices.",
	"Start installing the application for devices by selecting the corresponding devices. Select install to automatically start downloading the application for the respective devices.",
	"Start uninstalling the application for one or more users by selecting the corresponding user name.",
	"Start uninstalling the application for user ",
	"Select uninstall to automatically start uninstalling application for the respective user/users.",
	"Start installing the application for one or more users by selecting the corresponding user name.",
	"Start installing the application for for user ",
	"Select uninstall to automatically start downloading application for the respective user/users."]
